### ISSUE TITLE
./driver.sh is throwing error, instead of use default value.

### ISSUE THREAD

**Issue by depohmel** [GoogleCloudPlatform/marketplace-k8s-app-tools#163] opened 2018-07-03 00:06 UTC
Parametrs:
```
'--parameters={
  "name": "k10-kasten",
  "reportingSecret": "k10-kasten-reporintg-secret",
  "namespace": "default" 
}'
```
cpy/paste from schema.yaml
```
 tail -n 30 schema.yaml 
    deployerImage:
    type: string
    default: gcr.io//k10/deployer:1.1
    x-google-marketplace:
      type: IMAGE
required:
- name
- namespace
- serviceAccount.name
- metering.reportingSecret

- deployerImage
```

error:
```
Traceback (most recent call last):
  File "/bin/extract_schema_key.py", line 48, in <module>
    main()
  File "/bin/extract_schema_key.py", line 42, in main
    schema = config_helper.Schema.load_yaml_file(args.schema_file)
  File "/bin/config_helper.py", line 90, in load_yaml_file
    return Schema(d)
  File "/bin/config_helper.py", line 107, in __init__
    .format(', '.join(bad_required_names)))
config_helper.InvalidSchema: Undefined property names found in required:  deployerImage
```

I'm expecting for a driver to use default values from schema.yaml

**Comment by huyhg** [comment] 2018-08-01 23:11
I believe this was caused by a typo somewhere in `schema.yaml`. The error is saying that `deployerImage` property doesn't exist, yet it's listed in the `required` section.

Properties with default values are in fact not required to be included in the parameters passed to the verification binary.

I'm closing this issue now. Please re-open if you've found out otherwise.

**Closed by huyhg** 2018-08-01 23:11 UTC
